export type Kind = 'alphabet' | 'abjad' | 'abugida' | 'syllabary' | 'logographic';

export interface LanguageEntry {
  id: string;
  name: string;
  native: string;
  script: string;
  direction: 'ltr' | 'rtl';
  kind: Kind;
  letters: string[];
}

export const KIND_LABEL: Record<Kind, string> = {
  alphabet: 'Alphabet',
  abjad: 'Abjad (consonant script)',
  abugida: 'Abugida (syllabic alphabet)',
  syllabary: 'Syllabary',
  logographic: 'Logographic (sample characters)',
};

export const LANGUAGES: LanguageEntry[] = [
  {
    id: 'english',
    name: 'English',
    native: 'English',
    script: 'Latin',
    direction: 'ltr',
    kind: 'alphabet',
    letters: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split(''),
  },
  {
    id: 'spanish',
    name: 'Spanish',
    native: 'Español',
    script: 'Latin',
    direction: 'ltr',
    kind: 'alphabet',
    letters: 'ABCDEFGHIJKLMNÑOPQRSTUVWXYZ'.split(''),
  },
  {
    id: 'french',
    name: 'French',
    native: 'Français',
    script: 'Latin',
    direction: 'ltr',
    kind: 'alphabet',
    letters: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split(''),
  },
  {
    id: 'german',
    name: 'German',
    native: 'Deutsch',
    script: 'Latin',
    direction: 'ltr',
    kind: 'alphabet',
    letters: 'ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÜß'.split(''),
  },
  {
    id: 'portuguese',
    name: 'Portuguese',
    native: 'Português',
    script: 'Latin',
    direction: 'ltr',
    kind: 'alphabet',
    letters: 'ABCDEFGHIJKLMNOPQRSTUVWXYZÃÕÇ'.split(''),
  },
  {
    id: 'italian',
    name: 'Italian',
    native: 'Italiano',
    script: 'Latin',
    direction: 'ltr',
    kind: 'alphabet',
    letters: 'ABCDEFGHILMNOPQRSTUVZ'.split(''),
  },
  {
    id: 'vietnamese',
    name: 'Vietnamese',
    native: 'Tiếng Việt',
    script: 'Latin (extended)',
    direction: 'ltr',
    kind: 'alphabet',
    letters: 'A Ă Â B C D Đ E Ê G H I K L M N O Ô Ơ P Q R S T U Ư V X Y'.split(' '),
  },
  {
    id: 'turkish',
    name: 'Turkish',
    native: 'Türkçe',
    script: 'Latin',
    direction: 'ltr',
    kind: 'alphabet',
    letters: 'ABCÇDEFGĞHIİJKLMNOÖPRSŞTUÜVYZ'.split(''),
  },
  {
    id: 'polish',
    name: 'Polish',
    native: 'Polski',
    script: 'Latin',
    direction: 'ltr',
    kind: 'alphabet',
    letters: 'AĄBCĆDEĘFGHIJKLŁMNŃOÓPRSŚTUWYZŹŻ'.split(''),
  },
  {
    id: 'russian',
    name: 'Russian',
    native: 'Русский',
    script: 'Cyrillic',
    direction: 'ltr',
    kind: 'alphabet',
    letters: 'АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ'.split(''),
  },
  {
    id: 'ukrainian',
    name: 'Ukrainian',
    native: 'Українська',
    script: 'Cyrillic',
    direction: 'ltr',
    kind: 'alphabet',
    letters: 'АБВГҐДЕЄЖЗИІЇЙКЛМНОПРСТУФХЦЧШЩЬЮЯ'.split(''),
  },
  {
    id: 'serbian',
    name: 'Serbian',
    native: 'Српски',
    script: 'Cyrillic',
    direction: 'ltr',
    kind: 'alphabet',
    letters: 'АБВГДЂЕЖЗИЈКЛЉМНЊОПРСТЋУФХЦЧЏШ'.split(''),
  },
  {
    id: 'greek',
    name: 'Greek',
    native: 'Ελληνικά',
    script: 'Greek',
    direction: 'ltr',
    kind: 'alphabet',
    letters: 'ΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩ'.split(''),
  },
  {
    id: 'armenian',
    name: 'Armenian',
    native: 'Հայերեն',
    script: 'Armenian',
    direction: 'ltr',
    kind: 'alphabet',
    letters: 'ԱԲԳԴԵԶԷԸԹԺԻԼԽԾԿՀՁՂՃՄՅՆՇՈՉՊՋՌՍՎՏՐՑՒՓՔՕՖ'.split(''),
  },
  {
    id: 'georgian',
    name: 'Georgian',
    native: 'ქართული',
    script: 'Georgian',
    direction: 'ltr',
    kind: 'alphabet',
    letters: 'აბგდევზთიკლმნოპჟრსტუფქღყშჩცძწჭხჯჰ'.split(''),
  },
  {
    id: 'arabic',
    name: 'Arabic',
    native: 'العربية',
    script: 'Arabic',
    direction: 'rtl',
    kind: 'abjad',
    letters: 'ابتثجحخدذرزسشصضطظعغفقكلمنهوي'.split(''),
  },
  {
    id: 'persian',
    name: 'Persian',
    native: 'فارسی',
    script: 'Arabic (Perso-Arabic)',
    direction: 'rtl',
    kind: 'abjad',
    letters: 'ابپتثجچحخدذرزژسشصضطظعغفقکگلمنوهی'.split(''),
  },
  {
    id: 'urdu',
    name: 'Urdu',
    native: 'اردو',
    script: 'Arabic (Nastaliq)',
    direction: 'rtl',
    kind: 'abjad',
    letters: 'ابپتٹثجچحخدڈذرڑزژسشصضطظعغفقکگلمنوہی'.split(''),
  },
  {
    id: 'hebrew',
    name: 'Hebrew',
    native: 'עברית',
    script: 'Hebrew',
    direction: 'rtl',
    kind: 'abjad',
    letters: 'אבגדהוזחטיכלמנסעפצקרשת'.split(''),
  },
  {
    id: 'hindi',
    name: 'Hindi',
    native: 'हिन्दी',
    script: 'Devanagari',
    direction: 'ltr',
    kind: 'abugida',
    letters: 'अआइईउऊएऐओऔकखगघङचछजझञटठडढणतथदधनपफबभमयरलवशषसह'.split(''),
  },
  {
    id: 'marathi',
    name: 'Marathi',
    native: 'मराठी',
    script: 'Devanagari',
    direction: 'ltr',
    kind: 'abugida',
    letters: 'अआइईउऊएऐओऔकखगघचछजझटठडढतथदधनपफबभमयरलळवशषसह'.split(''),
  },
  {
    id: 'nepali',
    name: 'Nepali',
    native: 'नेपाली',
    script: 'Devanagari',
    direction: 'ltr',
    kind: 'abugida',
    letters: 'अआइईउऊएऐओऔकखगघङचछजझञटठडढणतथदधनपफबभमयरलवशषसह'.split(''),
  },
  {
    id: 'bengali',
    name: 'Bengali',
    native: 'বাংলা',
    script: 'Bengali',
    direction: 'ltr',
    kind: 'abugida',
    letters: 'অআইঈউঊএঐওঔকখগঘঙচছজঝঞটঠডঢণতথদধনপফবভমযরলশষসহ'.split(''),
  },
  {
    id: 'punjabi',
    name: 'Punjabi',
    native: 'ਪੰਜਾਬੀ',
    script: 'Gurmukhi',
    direction: 'ltr',
    kind: 'abugida',
    letters: 'ਅਆਇਈਉਊਏਐਓਔਕਖਗਘਙਚਛਜਝਞਟਠਡਢਣਤਥਦਧਨਪਫਬਭਮਯਰਲਵਸ਼ਹ'.split(''),
  },
  {
    id: 'gujarati',
    name: 'Gujarati',
    native: 'ગુજરાતી',
    script: 'Gujarati',
    direction: 'ltr',
    kind: 'abugida',
    letters: 'અઆઇઈઉઊએઐઓઔકખગઘઙચછજઝઞટઠડઢણતથદધનપફબભમયરલવશષસહ'.split(''),
  },
  {
    id: 'tamil',
    name: 'Tamil',
    native: 'தமிழ்',
    script: 'Tamil',
    direction: 'ltr',
    kind: 'abugida',
    letters: 'அஆஇஈஉஊஎஏஐஒஓஔகஙசஞடணதநபமயரலவழளறன'.split(''),
  },
  {
    id: 'telugu',
    name: 'Telugu',
    native: 'తెలుగు',
    script: 'Telugu',
    direction: 'ltr',
    kind: 'abugida',
    letters: 'అఆఇఈఉఊఎఏఐఒఓఔకఖగఘచఛజఝటఠడఢణతథదధనపఫబభమయరలవశషసహ'.split(''),
  },
  {
    id: 'kannada',
    name: 'Kannada',
    native: 'ಕನ್ನಡ',
    script: 'Kannada',
    direction: 'ltr',
    kind: 'abugida',
    letters: 'ಅಆಇಈಉಊಎಏಐಒಓಔಕಖಗಘಚಛಜಝಟಠಡಢಣತಥದಧನಪಫಬಭಮಯರಲವಶಷಸಹ'.split(''),
  },
  {
    id: 'malayalam',
    name: 'Malayalam',
    native: 'മലയാളം',
    script: 'Malayalam',
    direction: 'ltr',
    kind: 'abugida',
    letters: 'അആഇഈഉഊഎഏഐഒഓഔകഖഗഘങചഛജഝഞടഠഡഢണതഥദധനപഫബഭമയരലവശഷസഹ'.split(''),
  },
  {
    id: 'sinhala',
    name: 'Sinhala',
    native: 'සිංහල',
    script: 'Sinhala',
    direction: 'ltr',
    kind: 'abugida',
    letters: 'අආඇඈඉඊඋඌඑඒඓඔඕකඛගඝචඡජඣටඨඩඪතථදධනපඵබභමයරලවශෂසහළ'.split(''),
  },
  {
    id: 'thai',
    name: 'Thai',
    native: 'ไทย',
    script: 'Thai',
    direction: 'ltr',
    kind: 'abugida',
    letters: 'กขคงจฉชซญฎฏฐฑฒณดตถทธนบปผฝพฟภมยรลวศษสหฬอฮ'.split(''),
  },
  {
    id: 'lao',
    name: 'Lao',
    native: 'ລາວ',
    script: 'Lao',
    direction: 'ltr',
    kind: 'abugida',
    letters: 'ກຂຄງຈຊຍດຕຖທນບປຜຝພຟມຢຣລວສຫອຮ'.split(''),
  },
  {
    id: 'khmer',
    name: 'Khmer',
    native: 'ខ្មែរ',
    script: 'Khmer',
    direction: 'ltr',
    kind: 'abugida',
    letters: 'កខគឃងចឆជឈញដឋឌឍណតថទធនបផពភមយរលវសហឡអ'.split(''),
  },
  {
    id: 'burmese',
    name: 'Burmese',
    native: 'မြန်မာ',
    script: 'Myanmar',
    direction: 'ltr',
    kind: 'abugida',
    letters: 'ကခဂဃငစဆဇဈညဋဌဍဎဏတထဒဓနပဖဗဘမယရလဝသဟဠအ'.split(''),
  },
  {
    id: 'tibetan',
    name: 'Tibetan',
    native: 'བོད་སྐད',
    script: 'Tibetan',
    direction: 'ltr',
    kind: 'abugida',
    letters: 'ཀཁགངཅཆཇཉཏཐདནཔཕབམཙཚཛཝཞཟའཡརལཤསཧཨ'.split(''),
  },
  {
    id: 'amharic',
    name: 'Amharic',
    native: 'አማርኛ',
    script: "Ge'ez",
    direction: 'ltr',
    kind: 'abugida',
    letters: 'ሀለሐመሠረሰሸቀበተቸኀነኘአከኸወዐዘዠየደጀገጠጨጰጸፀፈፐ'.split(''),
  },
  {
    id: 'mongolian',
    name: 'Mongolian',
    native: 'Монгол',
    script: 'Mongolian',
    direction: 'ltr',
    kind: 'abugida',
    letters: 'ᠠᠡᠢᠣᠤᠥᠦᠧᠨᠩᠪᠫᠬᠭᠮᠯᠰᠱᠲᠳᠴᠵᠶᠷᠸᠹᠺᠻᠼᠽᠾᠿ'.split(''),
  },
  {
    id: 'japanese-hiragana',
    name: 'Japanese (Hiragana)',
    native: '日本語',
    script: 'Hiragana',
    direction: 'ltr',
    kind: 'syllabary',
    letters: 'あいうえおかきくけこさしすせそたちつてとなにぬねのはひふへほまみむめもやゆよらりるれろわをん'.split(''),
  },
  {
    id: 'japanese-katakana',
    name: 'Japanese (Katakana)',
    native: '日本語',
    script: 'Katakana',
    direction: 'ltr',
    kind: 'syllabary',
    letters: 'アイウエオカキクケコサシスセソタチツテトナニヌネノハヒフヘホマミムメモヤユヨラリルレロワヲン'.split(''),
  },
  {
    id: 'korean',
    name: 'Korean',
    native: '한국어',
    script: 'Hangul',
    direction: 'ltr',
    kind: 'alphabet',
    letters: 'ㄱㄴㄷㄹㅁㅂㅅㅇㅈㅊㅋㅌㅍㅎㅏㅑㅓㅕㅗㅛㅜㅠㅡㅣ'.split(''),
  },
  {
    id: 'chinese',
    name: 'Chinese (Mandarin)',
    native: '中文',
    script: 'Han (Hanzi)',
    direction: 'ltr',
    kind: 'logographic',
    letters: '人一大天日月水火山口木火土金木水火土人大天日月火水木金土人山口木水'
      .split('')
      .filter((v, i, a) => a.indexOf(v) === i),
  },
  {
    id: 'cherokee',
    name: 'Cherokee',
    native: 'ᏣᎳᎩ',
    script: 'Cherokee',
    direction: 'ltr',
    kind: 'syllabary',
    letters: 'ᎠᎡᎢᎣᎤᎥᎦᎧᎨᎩᎪᎫᎬᎭᎮᎯᎰᎱᎲᎳᎴᎵᎶᎷᎸᎹᎺᎻᎼᎽᎾ'.split(''),
  },
  {
    id: 'dutch',
    name: 'Dutch',
    native: 'Nederlands',
    script: 'Latin',
    direction: 'ltr',
    kind: 'alphabet',
    letters: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split(''),
  },
  {
    id: 'swahili',
    name: 'Swahili',
    native: 'Kiswahili',
    script: 'Latin',
    direction: 'ltr',
    kind: 'alphabet',
    letters: 'ABCDEFGHIJKLMNOPQRSTUVWYZ'.split(''),
  },
  {
    id: 'indonesian',
    name: 'Indonesian',
    native: 'Bahasa Indonesia',
    script: 'Latin',
    direction: 'ltr',
    kind: 'alphabet',
    letters: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split(''),
  },
];

export const SORTED_LANGUAGES = [...LANGUAGES].sort((a, b) => a.name.localeCompare(b.name));
