/** Representative phrases for script preview (not full translations). */
export const SAMPLE_TEXTS: Record<string, string> = {
  english: 'The quick brown fox jumps over the lazy dog.',
  spanish: 'El veloz murciélago hindú comía feliz cardillo y kiwi.',
  french: 'Portez ce vieux whisky au juge blond qui fume.',
  german: 'Victor jagt zwölf Boxkämpfer quer über den großen Sylter Deich.',
  portuguese: 'A rápida raposa marrom salta sobre o cão preguiçoso.',
  italian: 'Pranzo d’acqua fa volti sghembi.',
  vietnamese: 'Tôi yêu tiếng Việt và chữ Quốc ngữ.',
  turkish: 'Pijamalı hasta yağız şoföre çabucak güvendi.',
  polish: 'Zażółć gęślą jaźń.',
  russian: 'Все счастливые семьи похожи друг на друга.',
  ukrainian: 'Україна — країна з багатою мовою та культурою.',
  serbian: 'Све срећне породице личе једна на другу.',
  greek: 'Ξεσκεπάζω τὴν ψυχοφθόρα βδελυγμία.',
  armenian: 'Բոլոր մարդիկ ազատ են ծնվում հավասար:',
  georgian: 'ყველა ადამიანი იბადება თავისუფალი და თანასწორი.',
  arabic: 'السلام عليكم ورحمة الله وبركاته.',
  persian: 'زبان فارسی یکی از زیباترین زبان‌های جهان است.',
  urdu: 'اردو زبان بہت خوبصورت ہے۔',
  hebrew: 'שלום עולם, כל האנשים נולדו חופשיים.',
  hindi: 'हिन्दी भारत की राजभाषा है।',
  marathi: 'मराठी भाषा महाराष्ट्राची मातृभाषा आहे.',
  nepali: 'नेपाली नेपालको राष्ट्रिय भाषा हो।',
  bengali: 'আমি বাংলায় গান গাই।',
  punjabi: 'ਪੰਜਾਬੀ ਭਾਸ਼ਾ ਬਹੁਤ ਸੁੰਦਰ ਹੈ।',
  gujarati: 'ગુજરાતી ભાષા સુંદર છે.',
  tamil: 'தமிழ் உலகின் பழமையான மொழிகளில் ஒன்று.',
  telugu: 'తెలుగు భాష చాలా మధురమైనది.',
  kannada: 'ಕನ್ನಡ ನಮ್ಮ ಸೊಗಸಾದ ಭಾಷೆ.',
  malayalam: 'മലയാളം സുന്ദരമായ ഭാഷയാണ്.',
  sinhala: 'සිංහල ශ්‍රී ලංකාවේ ජාතික භාෂාවයි.',
  thai: 'ภาษาไทยเป็นภาษาราชการของประเทศไทย',
  lao: 'ພາສາລາວແມ່ນພາສາຂອງປະເທດລາວ.',
  khmer: 'ភាសាខ្មែរជាភាសាផ្លូវការនៅកម្ពុជា។',
  burmese: 'မြန်မာဘာသာစကားသည် လှပသော ဘာသာစကားဖြစ်သည်။',
  tibetan: 'བོད་ཡིག་ནི་བོད་ཀྱི་ཡི་གེ་རེད།',
  amharic: 'አማርኛ የኢትዮጵያ ቋንቋ ነው።',
  mongolian: 'ᠮᠣᠩᠭᠣᠯ ᠬᠡᠯᠡ ᠰᠣᠨᠢᠷᠬᠤ ᠬᠡᠯᠡ᠃',
  'japanese-hiragana': 'あいうえお — ひらがなのれんしゅうです。',
  'japanese-katakana': 'アイウエオ — カタカナの練習です。',
  korean: '한글은 세종대왕이 창제한 과학적인 문자입니다.',
  chinese: '天地人日月水火木金土 — 常用汉字示例。',
  cherokee: 'ᏣᎳᎩ ᎠᏂᏴᏫ ᎤᎾᏕᎾ ᎠᏍᏆᏂᎪᎢ.',
  dutch: 'Pa’s wijze lynx bezag vroom het fikse aquaduct.',
  swahili: 'Habari za asubuhi, lugha ni utajiri.',
  indonesian: 'Bahasa Indonesia adalah bahasa persatuan bangsa.',
};

export function getSampleText(languageId: string, native: string): string {
  return SAMPLE_TEXTS[languageId] ?? native;
}
