import type { LucideIcon } from 'lucide-react';
import {
  ALargeSmall,
  AudioWaveform,
  Binary,
  Code2,
  Fingerprint,
  CodeXml,
  FileCode,
  FileCode2,
  FileJson,
  FileSpreadsheet,
  FileText,
  FileType,
  Globe,
  Grid2X2,
  Grid3x3,
  Clapperboard,
  Image,
  ImagePlus,
  Images,
  Key,
  Layers,
  Lock,
  Palette,
  Pencil,
  PenLine,
  QrCode,
  Ruler,
  Type,
  BookOpen,
  Text,
  Languages,
  Pipette,
  Contrast,
  Tag,
  Blend,
  Square,
  Sparkles,
  LayoutGrid,
  LayoutTemplate,
} from 'lucide-react';

export type ToolCategory = 'Colour' | 'CSS' | 'Image' | 'Developer' | 'Text' | 'Converters';

export type Tool = {
  title: string;
  description: string;
  url: string;
  category: ToolCategory;
  icon: LucideIcon;
  featured?: boolean;
  badge?: 'New' | 'Beta';
};

export const tools: Tool[] = [
  {
    title: 'Palette Generator',
    description: 'Generate beautiful colour palettes',
    url: '/palette-generator',
    category: 'Colour',
    icon: Pencil,
    featured: true,
  },
  {
    title: 'Palette Collection',
    description: 'Browse and pick curated colour palettes',
    url: '/palette-collection',
    category: 'Colour',
    icon: Palette,
    featured: true,
  },
  {
    title: 'Colour Converter',
    description: 'Convert between colour formats',
    url: '/colour-converter',
    category: 'Colour',
    icon: Pipette,
    featured: true,
  },
  {
    title: 'Contrast Checker',
    description: 'Check WCAG colour contrast compliance',
    url: '/contrast-checker',
    category: 'Colour',
    icon: Contrast,
    featured: true,
  },
  {
    title: 'Tailwind Shade Generator',
    description: 'Generate Tailwind colour scales from any hex',
    url: '/tailwind-shade-generator',
    category: 'Colour',
    icon: AudioWaveform,
    featured: true,
  },
  {
    title: 'Gradient Generator',
    description: 'Create linear, corner, and mesh gradients',
    url: '/gradient-generator',
    category: 'CSS',
    icon: Blend,
    featured: true,
  },
  {
    title: 'Border Radius Generator',
    description: 'Design per-corner border-radius and copy CSS',
    url: '/border-radius-generator',
    category: 'CSS',
    icon: Square,
    featured: true,
    badge: 'New',
  },
  {
    title: 'Animation Generator',
    description: 'Design CSS keyframe animations with live preview and copy-ready code',
    url: '/animation-generator',
    category: 'CSS',
    icon: Clapperboard,
    featured: true,
    badge: 'New',
  },
  {
    title: 'Glassmorphism Generator',
    description: 'Build frosted-glass CSS with live preview',
    url: '/glassmorphism-generator',
    category: 'CSS',
    icon: Sparkles,
    featured: true,
    badge: 'New',
  },
  {
    title: 'Flex Patterns',
    description: '20 real-world flex layouts with copy-ready HTML and CSS',
    url: '/flex-patterns',
    category: 'CSS',
    icon: LayoutGrid,
    featured: true,
    badge: 'New',
  },
  {
    title: 'Placeholder Generator',
    description: 'Generate customisable placeholder images as PNG or SVG',
    url: '/placeholder-generator',
    category: 'Image',
    icon: Image,
    featured: true,
    badge: 'New',
  },
  {
    title: 'Image Converter',
    description: 'Convert between PNG, JPEG, WebP and more with resize options',
    url: '/image-converter',
    category: 'Image',
    icon: Images,
    featured: true,
    badge: 'New',
  },
  {
    title: 'Image Splitter',
    description: 'Split images into a custom grid of downloadable tiles',
    url: '/image-splitter',
    category: 'Image',
    icon: Grid2X2,
    featured: true,
    badge: 'New',
  },
  {
    title: 'Image Stitcher',
    description: 'Combine multiple images into one with row or grid layout',
    url: '/image-stitcher',
    category: 'Image',
    icon: Layers,
    featured: true,
    badge: 'New',
  },
  {
    title: 'Base64 Image Encoder',
    description: 'Convert images to Base64 strings for CSS/HTML embedding',
    url: '/base64-image-encoder',
    category: 'Image',
    icon: ImagePlus,
    featured: true,
    badge: 'New',
  },
  {
    title: 'Favicon Generator',
    description: 'Generate favicon sizes and HTML snippets from any image',
    url: '/favicon-generator',
    category: 'Image',
    icon: Globe,
    featured: true,
    badge: 'New',
  },
  {
    title: 'QR Code Generator',
    description: 'Generate customisable QR codes from any URL or text',
    url: '/qr-code-generator',
    category: 'Image',
    icon: QrCode,
    featured: true,
    badge: 'New',
  },
  {
    title: 'SVG Viewer',
    description: 'Paste SVG code and preview it live with zoom controls',
    url: '/svg-viewer',
    category: 'Image',
    icon: CodeXml,
    featured: true,
    badge: 'New',
  },
  {
    title: 'ASCII Art Generator',
    description: 'Convert images into ASCII art with adjustable resolution',
    url: '/ascii-art-generator',
    category: 'Image',
    icon: ALargeSmall,
    featured: true,
    badge: 'New',
  },
  {
    title: 'Code Snippet',
    description: 'Create and export styled code screenshots',
    url: '/code-snippet',
    category: 'Developer',
    icon: FileCode2,
    featured: true,
  },
  {
    title: 'Post Composer',
    description: 'Design social posts with text, shapes, and images',
    url: '/post-composer',
    category: 'Image',
    icon: LayoutTemplate,
    featured: true,
    badge: 'New',
  },
  {
    title: 'Image Annotator',
    description: 'Draw shapes, arrows, text, and highlights on images',
    url: '/image-annotator',
    category: 'Image',
    icon: PenLine,
    featured: true,
    badge: 'New',
  },
  {
    title: 'HTML Viewer',
    description: 'Live HTML preview with Tailwind and CSS support',
    url: '/html-viewer',
    category: 'Developer',
    icon: FileCode,
    featured: true,
    badge: 'New',
  },
  {
    title: 'Markdown Live Preview',
    description: 'Write markdown and preview it live side by side',
    url: '/markdown-live-preview',
    category: 'Developer',
    icon: FileText,
    featured: true,
    badge: 'New',
  },
  {
    title: 'JSON Viewer',
    description: 'Edit, search, and explore JSON with tree and raw views',
    url: '/json-viewer',
    category: 'Developer',
    icon: FileJson,
    featured: true,
    badge: 'New',
  },
  {
    title: 'CSV Viewer',
    description: 'Upload, search, sort, filter, and export CSV tables',
    url: '/csv-viewer',
    category: 'Developer',
    icon: FileSpreadsheet,
    featured: true,
    badge: 'New',
  },
  {
    title: 'Code Viewer',
    description: 'Local folder audit: insights, grep, TODOs/secrets, markdown & asset preview',
    url: '/code-viewer',
    category: 'Developer',
    icon: Code2,
    featured: true,
    badge: 'New',
  },
  {
    title: 'PDF Viewer',
    description: 'Preview, zoom, rotate, and navigate PDF files in the browser',
    url: '/pdf-viewer',
    category: 'Developer',
    icon: FileType,
    featured: true,
    badge: 'New',
  },
  {
    title: 'Meta Tag Generator',
    description: 'Generate HTML meta tags for SEO and social sharing',
    url: '/meta-tag-generator',
    category: 'Developer',
    icon: Tag,
    featured: true,
    badge: 'New',
  },
  {
    title: 'Word Counter',
    description: 'Count words, characters and more',
    url: '/word-counter',
    category: 'Text',
    icon: BookOpen,
    featured: true,
    badge: 'New',
  },
  {
    title: 'Lorem Ipsum Generator',
    description: 'Generate placeholder paragraphs as plain text or HTML',
    url: '/lorem-ipsum-generator',
    category: 'Text',
    icon: Type,
    featured: true,
    badge: 'New',
  },
  {
    title: 'Typography Calculator',
    description: 'Convert between typographic units',
    url: '/typography-calculator',
    category: 'Text',
    icon: Text,
    featured: true,
    badge: 'New',
  },
  {
    title: 'Glyph Browser',
    description: 'Browse Unicode glyphs by block with copy-friendly code formats',
    url: '/glyph-browser',
    category: 'Text',
    icon: Grid3x3,
    featured: true,
    badge: 'New',
  },
  {
    title: 'World Scripts',
    description: 'Explore alphabets and writing systems from around the world',
    url: '/world-scripts',
    category: 'Text',
    icon: Languages,
    featured: true,
    badge: 'New',
  },
  {
    title: 'Unit Converter',
    description: 'Convert between length, weight, area, data, temperature, and more',
    url: '/unit-converter',
    category: 'Converters',
    icon: Ruler,
    featured: true,
    badge: 'New',
  },
  {
    title: 'Base Converter',
    description: 'Convert between decimal, hex, binary, octal and bitwise ops',
    url: '/base-converter',
    category: 'Converters',
    icon: Binary,
    featured: true,
    badge: 'New',
  },
  {
    title: 'Password Generator',
    description: 'Create strong random passwords with length and character options',
    url: '/password-generator',
    category: 'Converters',
    icon: Lock,
    featured: true,
    badge: 'New',
  },
  {
    title: 'UUID Generator',
    description: 'Generate UUID v4 and v7 identifiers, including bulk lists',
    url: '/uuid-generator',
    category: 'Converters',
    icon: Fingerprint,
    featured: true,
    badge: 'New',
  },
  {
    title: 'JWT Decoder',
    description: 'Decode JWT tokens to inspect header, payload, and signature',
    url: '/jwt-decoder',
    category: 'Converters',
    icon: Key,
    featured: true,
    badge: 'New',
  },
];

export const toolCategories: ToolCategory[] = ['Colour', 'CSS', 'Image', 'Developer', 'Text', 'Converters'];

export const featuredTools = tools.filter((tool) => tool.featured);

export function toolsByCategory(category: ToolCategory) {
  return tools.filter((tool) => tool.category === category);
}
