export interface FlexItemConfig {
  label: string;
  width?: number | 'auto';
  height?: number | 'auto';
  flexGrow?: number;
  flexShrink?: number;
  flexBasis?: string;
  alignSelf?: string;
  minWidth?: number;
  minHeight?: number;
}

export interface FlexContainerConfig {
  flexDirection: string;
  flexWrap: string;
  justifyContent: string;
  alignItems: string;
  alignContent: string;
  gap: number;
  minHeight?: number;
  padding?: number;
}

export interface FlexPattern {
  id: string;
  name: string;
  description: string;
  container: FlexContainerConfig;
  items: FlexItemConfig[];
  /** Canvas size used for accurate scaled thumbnails */
  previewWidth: number;
  previewHeight: number;
}

export const FLEX_PATTERNS: FlexPattern[] = [
  {
    id: 'app-navbar',
    name: 'App Navbar',
    description: 'Logo, navigation links, and account action in a single header row',
    previewWidth: 400,
    previewHeight: 56,
    container: {
      flexDirection: 'row',
      flexWrap: 'nowrap',
      justifyContent: 'space-between',
      alignItems: 'center',
      alignContent: 'stretch',
      gap: 12,
      minHeight: 56,
      padding: 12,
    },
    items: [
      { label: 'Logo', width: 88, height: 32, flexShrink: 0 },
      { label: 'Home · Docs · Pricing', flexGrow: 1, height: 32 },
      { label: 'Sign in', width: 72, height: 32, flexShrink: 0 },
    ],
  },
  {
    id: 'sticky-footer-page',
    name: 'Sticky Footer Page',
    description: 'Full-height page shell where the main area grows and footer stays at the bottom',
    previewWidth: 360,
    previewHeight: 280,
    container: {
      flexDirection: 'column',
      flexWrap: 'nowrap',
      justifyContent: 'flex-start',
      alignItems: 'stretch',
      alignContent: 'stretch',
      gap: 0,
      minHeight: 280,
    },
    items: [
      { label: 'Header', height: 48, flexShrink: 0 },
      { label: 'Main content', flexGrow: 1, flexShrink: 1, flexBasis: '0', minHeight: 120 },
      { label: 'Footer', height: 40, flexShrink: 0 },
    ],
  },
  {
    id: 'sidebar-main',
    name: 'Sidebar + Main',
    description: 'Fixed-width sidebar with a fluid main content region',
    previewWidth: 400,
    previewHeight: 240,
    container: {
      flexDirection: 'row',
      flexWrap: 'nowrap',
      justifyContent: 'flex-start',
      alignItems: 'stretch',
      alignContent: 'stretch',
      gap: 0,
      minHeight: 240,
    },
    items: [
      { label: 'Sidebar', width: 120, flexShrink: 0 },
      { label: 'Main', flexGrow: 1, flexShrink: 1, flexBasis: '0' },
    ],
  },
  {
    id: 'split-editor',
    name: 'Split Editor Panel',
    description: 'Two equal panels for code editor and live preview side by side',
    previewWidth: 400,
    previewHeight: 220,
    container: {
      flexDirection: 'row',
      flexWrap: 'nowrap',
      justifyContent: 'flex-start',
      alignItems: 'stretch',
      alignContent: 'stretch',
      gap: 8,
      minHeight: 220,
      padding: 8,
    },
    items: [
      { label: 'Editor', flexGrow: 1, flexShrink: 1, flexBasis: '0' },
      { label: 'Preview', flexGrow: 1, flexShrink: 1, flexBasis: '0' },
    ],
  },
  {
    id: 'responsive-card-grid',
    name: 'Responsive Card Grid',
    description: 'Wrapping card row that reflows into multiple lines on smaller widths',
    previewWidth: 400,
    previewHeight: 200,
    container: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'flex-start',
      alignItems: 'stretch',
      alignContent: 'flex-start',
      gap: 12,
      minHeight: 200,
      padding: 12,
    },
    items: [
      { label: 'Card', flexGrow: 1, flexBasis: '120px', minWidth: 100, height: 72 },
      { label: 'Card', flexGrow: 1, flexBasis: '120px', minWidth: 100, height: 72 },
      { label: 'Card', flexGrow: 1, flexBasis: '120px', minWidth: 100, height: 72 },
      { label: 'Card', flexGrow: 1, flexBasis: '120px', minWidth: 100, height: 72 },
      { label: 'Card', flexGrow: 1, flexBasis: '120px', minWidth: 100, height: 72 },
    ],
  },
  {
    id: 'input-group',
    name: 'Input Group',
    description: 'Prefix addon, input field, and suffix action combined in one control',
    previewWidth: 360,
    previewHeight: 44,
    container: {
      flexDirection: 'row',
      flexWrap: 'nowrap',
      justifyContent: 'flex-start',
      alignItems: 'stretch',
      alignContent: 'stretch',
      gap: 0,
      minHeight: 44,
    },
    items: [
      { label: 'https://', width: 72, flexShrink: 0 },
      { label: 'domain.com', flexGrow: 1, flexShrink: 1, flexBasis: '0' },
      { label: 'Go', width: 48, flexShrink: 0 },
    ],
  },
  {
    id: 'button-toolbar',
    name: 'Button Toolbar',
    description: 'Grouped action buttons with consistent spacing in a toolbar row',
    previewWidth: 320,
    previewHeight: 44,
    container: {
      flexDirection: 'row',
      flexWrap: 'nowrap',
      justifyContent: 'flex-start',
      alignItems: 'center',
      alignContent: 'stretch',
      gap: 8,
      minHeight: 48,
      padding: 8,
    },
    items: [
      { label: 'Bold', width: 52, height: 32 },
      { label: 'Italic', width: 52, height: 32 },
      { label: 'Link', width: 52, height: 32 },
      { label: 'Code', width: 52, height: 32 },
    ],
  },
  {
    id: 'pagination-bar',
    name: 'Pagination Bar',
    description: 'Previous control, page numbers, and next control distributed across the row',
    previewWidth: 360,
    previewHeight: 44,
    container: {
      flexDirection: 'row',
      flexWrap: 'nowrap',
      justifyContent: 'space-between',
      alignItems: 'center',
      alignContent: 'stretch',
      gap: 12,
      minHeight: 44,
      padding: 12,
    },
    items: [
      { label: '← Prev', width: 64, height: 32 },
      { label: '1 · 2 · 3', width: 96, height: 32 },
      { label: 'Next →', width: 64, height: 32 },
    ],
  },
  {
    id: 'pricing-cards',
    name: 'Pricing Cards',
    description: 'Tier cards in a row with a highlighted plan centered in the layout',
    previewWidth: 400,
    previewHeight: 200,
    container: {
      flexDirection: 'row',
      flexWrap: 'nowrap',
      justifyContent: 'center',
      alignItems: 'stretch',
      alignContent: 'stretch',
      gap: 12,
      minHeight: 200,
      padding: 12,
    },
    items: [
      { label: 'Starter', width: 100, height: 160, flexGrow: 1, flexBasis: '100px' },
      { label: 'Pro', width: 110, height: 180, flexGrow: 1, flexBasis: '110px', alignSelf: 'center' },
      { label: 'Enterprise', width: 100, height: 160, flexGrow: 1, flexBasis: '100px' },
    ],
  },
  {
    id: 'chat-thread',
    name: 'Chat Thread',
    description: 'Vertical stack of message bubbles in a conversation panel',
    previewWidth: 320,
    previewHeight: 260,
    container: {
      flexDirection: 'column',
      flexWrap: 'nowrap',
      justifyContent: 'flex-end',
      alignItems: 'stretch',
      alignContent: 'stretch',
      gap: 10,
      minHeight: 260,
      padding: 12,
    },
    items: [
      { label: 'Hey, are we shipping today?', height: 40, alignSelf: 'flex-start', width: 200 },
      { label: 'Yes — release is at 5 PM', height: 40, alignSelf: 'flex-end', width: 180 },
      { label: 'Great, I will prep the changelog', height: 40, alignSelf: 'flex-start', width: 210 },
    ],
  },
  {
    id: 'modal-centered',
    name: 'Centered Modal',
    description: 'Dialog or empty-state card centered inside a full overlay region',
    previewWidth: 360,
    previewHeight: 240,
    container: {
      flexDirection: 'row',
      flexWrap: 'nowrap',
      justifyContent: 'center',
      alignItems: 'center',
      alignContent: 'stretch',
      gap: 0,
      minHeight: 240,
      padding: 16,
    },
    items: [{ label: 'Confirm delete?', width: 200, height: 120 }],
  },
  {
    id: 'tab-bar',
    name: 'Tab Bar',
    description: 'Evenly distributed tabs across the full width of a section header',
    previewWidth: 360,
    previewHeight: 44,
    container: {
      flexDirection: 'row',
      flexWrap: 'nowrap',
      justifyContent: 'space-evenly',
      alignItems: 'center',
      alignContent: 'stretch',
      gap: 8,
      minHeight: 48,
      padding: 8,
    },
    items: [
      { label: 'Overview', flexGrow: 1, height: 32 },
      { label: 'Analytics', flexGrow: 1, height: 32 },
      { label: 'Settings', flexGrow: 1, height: 32 },
    ],
  },
  {
    id: 'toast-stack',
    name: 'Toast Notification Stack',
    description: 'Notifications that stack upward from the bottom of the screen',
    previewWidth: 320,
    previewHeight: 220,
    container: {
      flexDirection: 'column-reverse',
      flexWrap: 'nowrap',
      justifyContent: 'flex-end',
      alignItems: 'stretch',
      alignContent: 'stretch',
      gap: 10,
      minHeight: 220,
      padding: 12,
    },
    items: [
      { label: 'File uploaded successfully', height: 48 },
      { label: 'New comment on your post', height: 48 },
      { label: 'Reminder: standup in 5 min', height: 48 },
    ],
  },
  {
    id: 'dialog-footer-actions',
    name: 'Dialog Footer Actions',
    description: 'Reversed button order so the primary action renders on the right while staying first in the DOM',
    previewWidth: 320,
    previewHeight: 64,
    container: {
      flexDirection: 'row-reverse',
      flexWrap: 'nowrap',
      justifyContent: 'flex-start',
      alignItems: 'center',
      alignContent: 'stretch',
      gap: 12,
      minHeight: 64,
      padding: 12,
    },
    items: [
      { label: 'Save changes', width: 120, height: 36, flexShrink: 0 },
      { label: 'Cancel', width: 80, height: 36, flexShrink: 0 },
      { label: 'Delete', width: 80, height: 36, flexShrink: 0 },
    ],
  },
  {
    id: 'price-display',
    name: 'Pricing Plan Price',
    description: 'Currency symbol, amount, and billing period aligned along their text baseline',
    previewWidth: 200,
    previewHeight: 64,
    container: {
      flexDirection: 'row',
      flexWrap: 'nowrap',
      justifyContent: 'flex-start',
      alignItems: 'baseline',
      alignContent: 'stretch',
      gap: 4,
      minHeight: 64,
      padding: 8,
    },
    items: [
      { label: '$', width: 16, flexShrink: 0 },
      { label: '49', width: 56, flexShrink: 0 },
      { label: '/ month', width: 64, flexShrink: 0, alignSelf: 'flex-end' },
    ],
  },
  {
    id: 'wizard-stepper',
    name: 'Wizard Stepper Progress',
    description: 'Step circles connected by lines that grow to fill the space between them',
    previewWidth: 400,
    previewHeight: 48,
    container: {
      flexDirection: 'row',
      flexWrap: 'nowrap',
      justifyContent: 'space-between',
      alignItems: 'center',
      alignContent: 'stretch',
      gap: 0,
      minHeight: 48,
      padding: 8,
    },
    items: [
      { label: '1', width: 32, height: 32, flexShrink: 0 },
      { label: 'Connector', flexGrow: 1, height: 2 },
      { label: '2', width: 32, height: 32, flexShrink: 0 },
      { label: 'Connector', flexGrow: 1, height: 2 },
      { label: '3', width: 32, height: 32, flexShrink: 0 },
    ],
  },
  {
    id: 'tag-chip-cloud',
    name: 'Tag Chip Cloud',
    description: 'Naturally-sized tags that wrap onto new lines without stretching to fill the row',
    previewWidth: 360,
    previewHeight: 120,
    container: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'flex-start',
      alignItems: 'flex-start',
      alignContent: 'flex-start',
      gap: 8,
      minHeight: 120,
      padding: 12,
    },
    items: [
      { label: 'react', width: 56, height: 28, flexShrink: 0 },
      { label: 'typescript', width: 84, height: 28, flexShrink: 0 },
      { label: 'tailwind', width: 72, height: 28, flexShrink: 0 },
      { label: 'design-systems', width: 116, height: 28, flexShrink: 0 },
      { label: 'accessibility', width: 96, height: 28, flexShrink: 0 },
      { label: 'testing', width: 64, height: 28, flexShrink: 0 },
    ],
  },
  {
    id: 'settings-menu-list',
    name: 'Settings Menu List',
    description: 'Uniform vertical list of navigation items in a settings sidebar',
    previewWidth: 220,
    previewHeight: 240,
    container: {
      flexDirection: 'column',
      flexWrap: 'nowrap',
      justifyContent: 'flex-start',
      alignItems: 'stretch',
      alignContent: 'stretch',
      gap: 4,
      minHeight: 240,
      padding: 8,
    },
    items: [
      { label: 'Profile', height: 40 },
      { label: 'Notifications', height: 40 },
      { label: 'Billing', height: 40 },
      { label: 'Security', height: 40 },
      { label: 'Integrations', height: 40 },
    ],
  },
  {
    id: 'photo-gallery-wall',
    name: 'Photo Gallery Wall',
    description: 'Fixed-size photo tiles distributed evenly across wrapped rows',
    previewWidth: 400,
    previewHeight: 220,
    container: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      alignItems: 'stretch',
      alignContent: 'space-between',
      gap: 8,
      minHeight: 220,
      padding: 12,
    },
    items: [
      { label: 'Photo', width: 90, height: 90, flexShrink: 0 },
      { label: 'Photo', width: 90, height: 90, flexShrink: 0 },
      { label: 'Photo', width: 90, height: 90, flexShrink: 0 },
      { label: 'Photo', width: 90, height: 90, flexShrink: 0 },
      { label: 'Photo', width: 90, height: 90, flexShrink: 0 },
      { label: 'Photo', width: 90, height: 90, flexShrink: 0 },
    ],
  },
  {
    id: 'feature-comparison-row',
    name: 'Feature Comparison Row',
    description: 'Equal fixed-width plan columns spaced evenly for a comparison table',
    previewWidth: 400,
    previewHeight: 160,
    container: {
      flexDirection: 'row',
      flexWrap: 'nowrap',
      justifyContent: 'space-around',
      alignItems: 'stretch',
      alignContent: 'stretch',
      gap: 0,
      minHeight: 160,
      padding: 8,
    },
    items: [
      { label: 'Free', width: 100, height: 140, flexShrink: 0 },
      { label: 'Team', width: 100, height: 140, flexShrink: 0 },
      { label: 'Business', width: 100, height: 140, flexShrink: 0 },
    ],
  },
];