import type { DesignPreset } from '../types';

const g = (value: string) => ({ type: 'gradient' as const, value });
const c = (value: string) => ({ type: 'color' as const, value });

export const DESIGN_PRESETS: DesignPreset[] = [
  {
    id: 'bold-gradient',
    name: 'Bold Gradient',
    category: 'Social',
    preview: 'linear-gradient(135deg,#6C5CE7,#00D9C0)',
    background: g('linear-gradient(135deg,#6C5CE7,#00D9C0)'),
    buildElements: (w, h) => [
      {
        type: 'shape',
        shapeType: 'circle',
        x: w * 0.55,
        y: h * 0.55,
        width: w * 0.55,
        height: w * 0.55,
        fill: '#FFFFFF',
        opacity: 0.08,
      },
      {
        type: 'text',
        x: w * 0.07,
        y: h * 0.62,
        width: w * 0.86,
        height: 180,
        text: 'Big ideas,\nsmall effort.',
        fontSize: 72,
        fontWeight: 800,
        fontFamily: 'Georgia, serif',
        color: '#FFFFFF',
        align: 'left',
      },
      {
        type: 'text',
        x: w * 0.07,
        y: h * 0.78,
        width: w * 0.7,
        height: 80,
        text: 'Design your next post in minutes.',
        fontSize: 28,
        fontWeight: 400,
        fontFamily: 'system-ui, sans-serif',
        color: '#E5E7EB',
        align: 'left',
      },
    ],
  },
  {
    id: 'minimal-light',
    name: 'Minimal Light',
    category: 'Minimal',
    preview: '#F5F1EA',
    background: c('#F5F1EA'),
    buildElements: (w, h) => [
      {
        type: 'text',
        x: w * 0.08,
        y: h * 0.35,
        width: w * 0.84,
        height: 200,
        text: 'Less noise.\nMore clarity.',
        fontSize: 64,
        fontWeight: 700,
        fontFamily: 'system-ui, sans-serif',
        color: '#111827',
        align: 'left',
      },
      {
        type: 'shape',
        shapeType: 'pill',
        x: w * 0.08,
        y: h * 0.58,
        width: 200,
        height: 48,
        fill: '#111827',
        opacity: 1,
      },
      {
        type: 'text',
        x: w * 0.08,
        y: h * 0.72,
        width: w * 0.6,
        height: 60,
        text: 'A clean canvas for your message.',
        fontSize: 22,
        fontWeight: 400,
        fontFamily: 'system-ui, sans-serif',
        color: '#6B7280',
        align: 'left',
      },
    ],
  },
  {
    id: 'dark-mode',
    name: 'Dark Mode',
    category: 'Minimal',
    preview: '#0B0D12',
    background: c('#0B0D12'),
    buildElements: (w, h) => [
      {
        type: 'shape',
        shapeType: 'rect',
        x: w * 0.06,
        y: h * 0.06,
        width: w * 0.88,
        height: h * 0.88,
        fill: '#FFFFFF',
        opacity: 0.04,
        radius: 24,
      },
      {
        type: 'text',
        x: w * 0.1,
        y: h * 0.38,
        width: w * 0.8,
        height: 160,
        text: 'Build in the dark.',
        fontSize: 68,
        fontWeight: 800,
        fontFamily: 'system-ui, sans-serif',
        color: '#F9FAFB',
        align: 'left',
      },
      {
        type: 'text',
        x: w * 0.1,
        y: h * 0.55,
        width: w * 0.75,
        height: 80,
        text: 'Ship faster with focused design.',
        fontSize: 26,
        fontWeight: 400,
        fontFamily: 'system-ui, sans-serif',
        color: '#9CA3AF',
        align: 'left',
      },
    ],
  },
  {
    id: 'sunset-glow',
    name: 'Sunset Glow',
    category: 'Social',
    preview: 'linear-gradient(135deg,#FF6B4A,#FFD166)',
    background: g('linear-gradient(135deg,#FF6B4A,#FFD166)'),
    buildElements: (w, h) => [
      {
        type: 'text',
        x: w * 0.08,
        y: h * 0.3,
        width: w * 0.84,
        height: 200,
        text: 'Golden hour\nenergy',
        fontSize: 76,
        fontWeight: 800,
        fontFamily: 'Georgia, serif',
        color: '#FFFFFF',
        align: 'center',
      },
      {
        type: 'shape',
        shapeType: 'star',
        x: w * 0.4,
        y: h * 0.62,
        width: 120,
        height: 120,
        fill: '#FFFFFF',
        opacity: 0.25,
      },
    ],
  },
  {
    id: 'ocean-breeze',
    name: 'Ocean Breeze',
    category: 'Social',
    preview: 'linear-gradient(135deg,#0EA5E9,#22D3EE)',
    background: g('linear-gradient(135deg,#0EA5E9,#22D3EE)'),
    buildElements: (w, h) => [
      {
        type: 'shape',
        shapeType: 'circle',
        x: -w * 0.15,
        y: h * 0.65,
        width: w * 0.5,
        height: w * 0.5,
        fill: '#FFFFFF',
        opacity: 0.12,
      },
      {
        type: 'text',
        x: w * 0.08,
        y: h * 0.32,
        width: w * 0.84,
        height: 180,
        text: 'Ride the wave',
        fontSize: 70,
        fontWeight: 800,
        fontFamily: 'system-ui, sans-serif',
        color: '#FFFFFF',
        align: 'left',
      },
      {
        type: 'text',
        x: w * 0.08,
        y: h * 0.5,
        width: w * 0.7,
        height: 60,
        text: 'Fresh ideas. Cool vibes.',
        fontSize: 26,
        fontWeight: 400,
        fontFamily: 'system-ui, sans-serif',
        color: '#E0F2FE',
        align: 'left',
      },
    ],
  },
  {
    id: 'forest-calm',
    name: 'Forest Calm',
    category: 'Nature',
    preview: 'linear-gradient(160deg,#134E4A,#0F766E)',
    background: g('linear-gradient(160deg,#134E4A,#0F766E)'),
    buildElements: (w, h) => [
      {
        type: 'text',
        x: w * 0.08,
        y: h * 0.35,
        width: w * 0.84,
        height: 160,
        text: 'Grow slowly.\nBloom boldly.',
        fontSize: 60,
        fontWeight: 700,
        fontFamily: 'Georgia, serif',
        color: '#ECFDF5',
        align: 'left',
      },
      {
        type: 'shape',
        shapeType: 'hexagon',
        x: w * 0.72,
        y: h * 0.12,
        width: 140,
        height: 140,
        fill: '#FFFFFF',
        opacity: 0.1,
      },
    ],
  },
  {
    id: 'corporate-blue',
    name: 'Corporate Blue',
    category: 'Business',
    preview: 'linear-gradient(135deg,#1E3A8A,#3B82F6)',
    background: g('linear-gradient(135deg,#1E3A8A,#3B82F6)'),
    buildElements: (w, h) => [
      {
        type: 'text',
        x: w * 0.08,
        y: h * 0.28,
        width: w * 0.84,
        height: 120,
        text: 'Quarterly Update',
        fontSize: 48,
        fontWeight: 600,
        fontFamily: 'system-ui, sans-serif',
        color: '#BFDBFE',
        align: 'left',
      },
      {
        type: 'text',
        x: w * 0.08,
        y: h * 0.42,
        width: w * 0.84,
        height: 200,
        text: 'Results that\nspeak volumes',
        fontSize: 64,
        fontWeight: 800,
        fontFamily: 'system-ui, sans-serif',
        color: '#FFFFFF',
        align: 'left',
      },
      {
        type: 'shape',
        shapeType: 'rect',
        x: w * 0.08,
        y: h * 0.72,
        width: 180,
        height: 4,
        fill: '#FFFFFF',
        opacity: 0.6,
      },
    ],
  },
  {
    id: 'quote-card',
    name: 'Quote Card',
    category: 'Social',
    preview: '#FFFFFF',
    background: c('#FFFFFF'),
    buildElements: (w, h) => [
      {
        type: 'shape',
        shapeType: 'rect',
        x: w * 0.06,
        y: h * 0.06,
        width: w * 0.88,
        height: h * 0.88,
        fill: '#F3F4F6',
        opacity: 1,
        radius: 20,
      },
      {
        type: 'text',
        x: w * 0.12,
        y: h * 0.32,
        width: w * 0.76,
        height: 240,
        text: '"Design is not just what it looks like — design is how it works."',
        fontSize: 36,
        fontWeight: 500,
        fontFamily: 'Georgia, serif',
        color: '#111827',
        align: 'center',
      },
      {
        type: 'text',
        x: w * 0.12,
        y: h * 0.68,
        width: w * 0.76,
        height: 40,
        text: '— Steve Jobs',
        fontSize: 20,
        fontWeight: 600,
        fontFamily: 'system-ui, sans-serif',
        color: '#6B7280',
        align: 'center',
      },
    ],
  },
  {
    id: 'product-launch',
    name: 'Product Launch',
    category: 'Business',
    preview: 'linear-gradient(135deg,#111827,#374151)',
    background: g('linear-gradient(135deg,#111827,#374151)'),
    buildElements: (w, h) => [
      {
        type: 'shape',
        shapeType: 'pill',
        x: w * 0.08,
        y: h * 0.12,
        width: 160,
        height: 36,
        fill: '#14E8B4',
        opacity: 1,
      },
      {
        type: 'text',
        x: w * 0.08,
        y: h * 0.22,
        width: w * 0.84,
        height: 200,
        text: 'Introducing\nSomething New',
        fontSize: 68,
        fontWeight: 800,
        fontFamily: 'system-ui, sans-serif',
        color: '#FFFFFF',
        align: 'left',
      },
      {
        type: 'text',
        x: w * 0.08,
        y: h * 0.52,
        width: w * 0.7,
        height: 80,
        text: 'Available now. Limited early access.',
        fontSize: 24,
        fontWeight: 400,
        fontFamily: 'system-ui, sans-serif',
        color: '#D1D5DB',
        align: 'left',
      },
      {
        type: 'shape',
        shapeType: 'arrow',
        x: w * 0.08,
        y: h * 0.68,
        width: 120,
        height: 60,
        fill: '#14E8B4',
        opacity: 1,
      },
    ],
  },
  {
    id: 'event-announce',
    name: 'Event Announce',
    category: 'Business',
    preview: 'linear-gradient(135deg,#7C3AED,#EC4899)',
    background: g('linear-gradient(135deg,#7C3AED,#EC4899)'),
    buildElements: (w, h) => [
      {
        type: 'text',
        x: w * 0.08,
        y: h * 0.15,
        width: w * 0.84,
        height: 60,
        text: "YOU'RE INVITED",
        fontSize: 22,
        fontWeight: 700,
        fontFamily: 'system-ui, sans-serif',
        color: '#F5D0FE',
        align: 'center',
        letterSpacing: 4,
      },
      {
        type: 'text',
        x: w * 0.08,
        y: h * 0.28,
        width: w * 0.84,
        height: 200,
        text: 'Design Meetup\n2026',
        fontSize: 72,
        fontWeight: 800,
        fontFamily: 'system-ui, sans-serif',
        color: '#FFFFFF',
        align: 'center',
      },
      {
        type: 'text',
        x: w * 0.08,
        y: h * 0.58,
        width: w * 0.84,
        height: 60,
        text: 'Aug 15 · 6 PM · Virtual',
        fontSize: 24,
        fontWeight: 500,
        fontFamily: 'system-ui, sans-serif',
        color: '#FCE7F3',
        align: 'center',
      },
    ],
  },
  {
    id: 'tips-tricks',
    name: 'Tips & Tricks',
    category: 'Social',
    preview: '#FEF3C7',
    background: c('#FEF3C7'),
    buildElements: (w, h) => [
      {
        type: 'shape',
        shapeType: 'circle',
        x: w * 0.08,
        y: h * 0.1,
        width: 64,
        height: 64,
        fill: '#F59E0B',
        opacity: 1,
      },
      {
        type: 'text',
        x: w * 0.08,
        y: h * 0.22,
        width: w * 0.84,
        height: 80,
        text: '3 Quick Tips',
        fontSize: 52,
        fontWeight: 800,
        fontFamily: 'system-ui, sans-serif',
        color: '#92400E',
        align: 'left',
      },
      {
        type: 'text',
        x: w * 0.08,
        y: h * 0.38,
        width: w * 0.84,
        height: 280,
        text: '1. Keep it simple\n2. Use contrast\n3. One idea per slide',
        fontSize: 32,
        fontWeight: 500,
        fontFamily: 'system-ui, sans-serif',
        color: '#78350F',
        align: 'left',
        lineHeight: 1.6,
      },
    ],
  },
  {
    id: 'testimonial',
    name: 'Testimonial',
    category: 'Business',
    preview: 'linear-gradient(135deg,#1E293B,#334155)',
    background: g('linear-gradient(135deg,#1E293B,#334155)'),
    buildElements: (w, h) => [
      {
        type: 'shape',
        shapeType: 'circle',
        x: w * 0.08,
        y: h * 0.15,
        width: 80,
        height: 80,
        fill: '#14E8B4',
        opacity: 1,
      },
      {
        type: 'text',
        x: w * 0.08,
        y: h * 0.32,
        width: w * 0.84,
        height: 200,
        text: '"This tool saved us hours every week. Our team loves it."',
        fontSize: 34,
        fontWeight: 500,
        fontFamily: 'Georgia, serif',
        color: '#F1F5F9',
        align: 'left',
      },
      {
        type: 'text',
        x: w * 0.08,
        y: h * 0.62,
        width: w * 0.84,
        height: 40,
        text: 'Sarah Chen · Product Lead',
        fontSize: 20,
        fontWeight: 600,
        fontFamily: 'system-ui, sans-serif',
        color: '#94A3B8',
        align: 'left',
      },
    ],
  },
  {
    id: 'sale-promo',
    name: 'Sale Promo',
    category: 'Social',
    preview: 'linear-gradient(135deg,#DC2626,#F97316)',
    background: g('linear-gradient(135deg,#DC2626,#F97316)'),
    buildElements: (w, h) => [
      {
        type: 'text',
        x: w * 0.05,
        y: h * 0.2,
        width: w * 0.9,
        height: 200,
        text: '50% OFF',
        fontSize: 96,
        fontWeight: 900,
        fontFamily: 'system-ui, sans-serif',
        color: '#FFFFFF',
        align: 'center',
      },
      {
        type: 'text',
        x: w * 0.05,
        y: h * 0.48,
        width: w * 0.9,
        height: 60,
        text: 'This weekend only',
        fontSize: 28,
        fontWeight: 500,
        fontFamily: 'system-ui, sans-serif',
        color: '#FEE2E2',
        align: 'center',
      },
      {
        type: 'shape',
        shapeType: 'star',
        x: w * 0.78,
        y: h * 0.08,
        width: 80,
        height: 80,
        fill: '#FDE047',
        opacity: 0.9,
      },
    ],
  },
  {
    id: 'podcast-cover',
    name: 'Podcast Cover',
    category: 'Creative',
    preview: 'linear-gradient(135deg,#4C1D95,#7C3AED)',
    background: g('linear-gradient(135deg,#4C1D95,#7C3AED)'),
    buildElements: (w, h) => [
      {
        type: 'shape',
        shapeType: 'circle',
        x: w * 0.25,
        y: h * 0.2,
        width: w * 0.5,
        height: w * 0.5,
        fill: '#FFFFFF',
        opacity: 0.1,
      },
      {
        type: 'text',
        x: w * 0.08,
        y: h * 0.55,
        width: w * 0.84,
        height: 120,
        text: 'The Daily\nCreative',
        fontSize: 56,
        fontWeight: 800,
        fontFamily: 'system-ui, sans-serif',
        color: '#FFFFFF',
        align: 'center',
      },
      {
        type: 'text',
        x: w * 0.08,
        y: h * 0.75,
        width: w * 0.84,
        height: 40,
        text: 'Episode 42 · New every Tuesday',
        fontSize: 18,
        fontWeight: 400,
        fontFamily: 'system-ui, sans-serif',
        color: '#DDD6FE',
        align: 'center',
      },
    ],
  },
  {
    id: 'newsletter',
    name: 'Newsletter',
    category: 'Business',
    preview: '#FFFBEB',
    background: c('#FFFBEB'),
    buildElements: (w, h) => [
      {
        type: 'text',
        x: w * 0.08,
        y: h * 0.15,
        width: w * 0.84,
        height: 60,
        text: 'WEEKLY DIGEST',
        fontSize: 18,
        fontWeight: 700,
        fontFamily: 'system-ui, sans-serif',
        color: '#B45309',
        align: 'left',
        letterSpacing: 3,
      },
      {
        type: 'text',
        x: w * 0.08,
        y: h * 0.25,
        width: w * 0.84,
        height: 200,
        text: '5 trends shaping\ndesign in 2026',
        fontSize: 56,
        fontWeight: 800,
        fontFamily: 'Georgia, serif',
        color: '#1C1917',
        align: 'left',
      },
      {
        type: 'shape',
        shapeType: 'rect',
        x: w * 0.08,
        y: h * 0.58,
        width: w * 0.84,
        height: 2,
        fill: '#D6D3D1',
        opacity: 1,
      },
      {
        type: 'text',
        x: w * 0.08,
        y: h * 0.62,
        width: w * 0.84,
        height: 80,
        text: 'Read the full breakdown inside →',
        fontSize: 22,
        fontWeight: 500,
        fontFamily: 'system-ui, sans-serif',
        color: '#78716C',
        align: 'left',
      },
    ],
  },
  {
    id: 'linkedin-thought',
    name: 'LinkedIn Thought',
    category: 'Business',
    preview: '#FFFFFF',
    background: c('#FFFFFF'),
    buildElements: (w, h) => [
      { type: 'shape', shapeType: 'rect', x: 0, y: 0, width: w, height: 8, fill: '#0A66C2', opacity: 1, radius: 0 },
      {
        type: 'text',
        x: w * 0.08,
        y: h * 0.2,
        width: w * 0.84,
        height: 280,
        text: "The best designers I know don't chase trends.\n\nThey solve problems.",
        fontSize: 36,
        fontWeight: 600,
        fontFamily: 'system-ui, sans-serif',
        color: '#1F2937',
        align: 'left',
        lineHeight: 1.5,
      },
      {
        type: 'text',
        x: w * 0.08,
        y: h * 0.72,
        width: w * 0.84,
        height: 40,
        text: 'Agree? Share your take below.',
        fontSize: 20,
        fontWeight: 400,
        fontFamily: 'system-ui, sans-serif',
        color: '#6B7280',
        align: 'left',
      },
    ],
  },
  {
    id: 'motivational',
    name: 'Motivational',
    category: 'Social',
    preview: 'linear-gradient(135deg,#FF4D6D,#7C5CFF)',
    background: g('linear-gradient(135deg,#FF4D6D,#7C5CFF)'),
    buildElements: (w, h) => [
      {
        type: 'text',
        x: w * 0.08,
        y: h * 0.35,
        width: w * 0.84,
        height: 240,
        text: "Start before\nyou're ready.",
        fontSize: 72,
        fontWeight: 900,
        fontFamily: 'system-ui, sans-serif',
        color: '#FFFFFF',
        align: 'center',
      },
      {
        type: 'shape',
        shapeType: 'heart',
        x: w * 0.44,
        y: h * 0.68,
        width: 80,
        height: 80,
        fill: '#FFFFFF',
        opacity: 0.3,
      },
    ],
  },
  {
    id: 'tech-startup',
    name: 'Tech Startup',
    category: 'Business',
    preview: '#0F172A',
    background: c('#0F172A'),
    buildElements: (w, h) => [
      {
        type: 'shape',
        shapeType: 'diamond',
        x: w * 0.08,
        y: h * 0.1,
        width: 60,
        height: 60,
        fill: '#14E8B4',
        opacity: 1,
      },
      {
        type: 'text',
        x: w * 0.08,
        y: h * 0.22,
        width: w * 0.84,
        height: 180,
        text: 'Ship. Learn.\nIterate.',
        fontSize: 64,
        fontWeight: 800,
        fontFamily: 'system-ui, sans-serif',
        color: '#F8FAFC',
        align: 'left',
      },
      {
        type: 'text',
        x: w * 0.08,
        y: h * 0.48,
        width: w * 0.75,
        height: 80,
        text: 'Building the future of creative tools.',
        fontSize: 24,
        fontWeight: 400,
        fontFamily: 'system-ui, sans-serif',
        color: '#64748B',
        align: 'left',
      },
      {
        type: 'shape',
        shapeType: 'pill',
        x: w * 0.08,
        y: h * 0.62,
        width: 200,
        height: 44,
        fill: '#14E8B4',
        opacity: 1,
      },
    ],
  },
  {
    id: 'split-layout',
    name: 'Split Layout',
    category: 'Creative',
    preview: 'linear-gradient(90deg,#111827 50%,#F5F1EA 50%)',
    background: g('linear-gradient(90deg,#111827 50%,#F5F1EA 50%)'),
    buildElements: (w, h) => [
      {
        type: 'text',
        x: w * 0.06,
        y: h * 0.38,
        width: w * 0.4,
        height: 200,
        text: 'Before',
        fontSize: 48,
        fontWeight: 800,
        fontFamily: 'system-ui, sans-serif',
        color: '#FFFFFF',
        align: 'center',
      },
      {
        type: 'text',
        x: w * 0.54,
        y: h * 0.38,
        width: w * 0.4,
        height: 200,
        text: 'After',
        fontSize: 48,
        fontWeight: 800,
        fontFamily: 'system-ui, sans-serif',
        color: '#111827',
        align: 'center',
      },
    ],
  },
  {
    id: 'neon-nights',
    name: 'Neon Nights',
    category: 'Creative',
    preview: 'linear-gradient(160deg,#0F2027,#203A43,#2C5364)',
    background: g('linear-gradient(160deg,#0F2027,#203A43,#2C5364)'),
    buildElements: (w, h) => [
      {
        type: 'shape',
        shapeType: 'circle',
        x: w * 0.65,
        y: h * 0.08,
        width: 200,
        height: 200,
        fill: '#14E8B4',
        opacity: 0.15,
      },
      {
        type: 'shape',
        shapeType: 'circle',
        x: w * 0.05,
        y: h * 0.55,
        width: 160,
        height: 160,
        fill: '#A855F7',
        opacity: 0.12,
      },
      {
        type: 'text',
        x: w * 0.08,
        y: h * 0.35,
        width: w * 0.84,
        height: 180,
        text: 'Neon Nights',
        fontSize: 68,
        fontWeight: 800,
        fontFamily: 'system-ui, sans-serif',
        color: '#14E8B4',
        align: 'left',
      },
      {
        type: 'text',
        x: w * 0.08,
        y: h * 0.55,
        width: w * 0.7,
        height: 60,
        text: 'Create after dark.',
        fontSize: 26,
        fontWeight: 400,
        fontFamily: 'system-ui, sans-serif',
        color: '#94A3B8',
        align: 'left',
      },
    ],
  },
];

export const PRESET_CATEGORIES = [...new Set(DESIGN_PRESETS.map((p) => p.category))];
