export const NAME_PARTS_A = [
  'Mayfair',
  'Piccadilly',
  'Bond Street',
  'Leicester Square',
  'Temple',
  'Westminster',
  'South Kensington',
  'Hampstead',
  'Sloane Square',
  'Tower Hill',
  'Baker Street',
  'Green Park',
  'Holland Park',
  'Notting Hill Gate',
  "Regent's Park",
  'Bank',
  'Chelsea',
  'Camden',
  'Shoreditch',
  'Islington',
  'Marylebone',
  'Fitzrovia',
  'Bloomsbury',
  'Clerkenwell',
  'Southwark',
  'Greenwich',
  'Richmond',
  'Kew',
  'Highgate',
  'Primrose Hill',
  'Covent Garden',
  'Soho',
  'Mayflower',
  'Spitalfields',
  'Whitechapel',
  'Wapping',
  'Bermondsey',
  'Peckham',
  'Brixton',
  'Clapham',
  'Battersea',
  'Fulham',
  'Putney',
  'Wimbledon',
  'Ealing',
  'Acton',
  'Chiswick',
  'Hammersmith',
  'Kensington',
  'Belgravia',
  'Pimlico',
  'Vauxhall',
  'Lambeth',
  'Waterloo',
  'Blackfriars',
  'Farringdon',
  'Barbican',
  'Angel',
  'Dalston',
  'Hackney',
  'Bow',
  'Stratford',
  'Woolwich',
  'Blackheath',
  'Dulwich',
  'Streatham',
  'Tooting',
  'Barnes',
  'Hounslow',
  'Twickenham',
  'Harrow',
  'Wembley',
  'Finchley',
  'Muswell Hill',
  'Crouch End',
  'Archway',
  'Holloway',
  'Kentish Town',
  'Tufnell Park',
  'Willesden',
  'Kilburn',
  'Maida Vale',
  'Paddington',
  'Bayswater',
  'Earls Court',
  'West Brompton',
  'Knightsbridge',
];

export const NAME_PARTS_B = [
  'Gardens',
  'Yard',
  'Row',
  'Court',
  'Bridge',
  'Wharf',
  'Common',
  'Heath',
  'Green',
  'Mews',
  'Terrace',
  'Fields',
  'Quay',
  'Crescent',
  'Walk',
];
