export const NAME_BANK = [
  'Shadows Of Time',
  'Flood',
  'I Love You Pink',
  'Windy Meadow',
  'Ocean Drift',
  'Copper Dusk',
  'Velvet Night',
  'Golden Hour',
  'Sea Glass',
  'Rustic Clay',
  'Moonlit Path',
  'Autumn Ember',
  'Sage Whisper',
  'Coral Reef',
  'Deep Forest',
  'Blush Wine',
  'Storm Cloud',
  'Honey Glow',
  'Frosted Mint',
  'Dusty Rose',
  'Amber Fields',
  'Twilight Haze',
  'Cobalt Dream',
  'Sandstone',
  'Lavender Fog',
  'Crimson Tide',
  'Olive Grove',
  'Slate Harbor',
  'Peach Sorbet',
  'Iron Horizon',
  'Faded Denim',
  'Sunlit Wheat',
  'Ash Rose',
  'Pine Shadow',
  'Terracotta Sun',
  'Quiet Glacier',
  'Wild Fig',
  'Brass Ember',
  'Nightshade',
  'Chalk Dust',
] as const;

export const MIN_COLORS = 3;
export const MAX_COLORS = 8;
export const DEFAULT_COLOR_COUNT = 5;
